services:
  app:
    build:
      dockerfile: ./Dockerfile
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    environment:
      - CARGO_TARGET_DIR=/target
    volumes:
      - .:/app

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: ###
      MYSQL_USER: ###
      MYSQL_PASSWORD: ###
      MYSQL_ROOT_PASSWORD: ###
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 33006:3306

  adminer:
      image: adminer
      restart: always
      ports:
        - 9000:8080

  nginx:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default
    ports:
      - 8080:80


volumes:
  db_data: