services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - app_data:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ###
      MYSQL_DATABASE: ###
      MYSQL_USER: ###
      MYSQL_PASSWORD: ###
    volumes:
      - db_data:/var/lib/mysql

  php-fpm:
    image: PATH_TO_YOUR_PROD_IMAGE
    volumes:
      - app_data:/var/www/html

volumes:
  db_data:
  app_data:
